In [1]:
from google_images_download import google_images_download

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import cv2

In [3]:
def download_image_from_google(imageName,count):
    response=google_images_download.googleimagesdownload()
    arguements={"keywords":imageName,"limit":count}
    path=response.download(arguements)
    print(path)

In [16]:
download_image_from_google("juicy_apple_jpg",100)


Item no.: 1 --> Item name = juicy_apple_jpg
Evaluating...
Starting Download...
Completed Image ====> 1.15554020-juicy-apple-with-slice.jpg
Completed Image ====> 2.juicy-green-apple-5575032.jpg
URLError on an image...trying next one... Error: HTTP Error 403: Forbidden
Completed Image ====> 3.granny-smith-apple.jpg
Completed Image ====> 4.green-juicy-apple-vector-635088.jpg
Completed Image ====> 5.500_F_106932717_J0UIDicqyGc3KlhK3AYIHGDaHwChZn9i.jpg
Completed Image ====> 6.103153149-a-fruit-orchard-with-plenty-number-of-big-red-juicy-apple-in-the-sunlight.jpg
Completed Image ====> 7.beautiful-single-red-juicy-apple-one-image-is-sliced-horizontally-with-purple-flower-PKWAX1.jpg
Completed Image ====> 8.bright-of-colorful-juicy-apple-vector-21698885.jpg
Completed Image ====> 9.juicy-apple-with-a-beautiful-apple-half-showing-the-core-house-red-nice-color-RPC7NJ.jpg
Completed Image ====> 10.apple-rotate-still-1400x788.jpg
URLError on an image...trying next one... Error: HTTP Error 403: Forbi

In [ ]:
download_image_from_google("mango_jpg",100)


Item no.: 1 --> Item name = mango_jpg
Evaluating...
Starting Download...
Completed Image ====> 1.Mango_BNC.jpg
Completed Image ====> 2.Mango_4.jpg
Completed Image ====> 3.6270mango.jpg
Completed Image ====> 4.Mango_and_cross_section_edit.jpg
Completed Image ====> 5.Mango_hedgehog.jpg
Completed Image ====> 6.depositphotos_36983317-stock-photo-mango.jpg
Completed Image ====> 7.2480153-mango.jpg
Completed Image ====> 8.National-Fruit-ili-71-img-7.jpg
Completed Image ====> 9.mango-6.jpg
Completed Image ====> 10.mango.jpg
Completed Image ====> 11.cut+mango.jpg
Completed Image ====> 12.mango.jpg
Completed Image ====> 13.Big_mango.jpg
Completed Image ====> 14.buy-ratnagiri-alphonso-mango.jpg
Completed Image ====> 15.Green_mango.jpg
Completed Image ====> 16.National-Fruit-ili-71-img-1.jpg
Completed Image ====> 17.mango.jpg
Completed Image ====> 18.mango.jpg
Completed Image ====> 19.health-benefits-of-mango-200-200.jpg
Completed Image ====> 20.mango.jpg
Completed Image ====> 21.manga-assortime

In [4]:
image_dir=os.listdir('downloads/')

In [5]:
image_dir

['cat_jpg', 'dog_jpg']

In [6]:
all_cat_image_names=os.listdir('downloads/cat_jpg/')
all_dog_image_names=os.listdir('downloads/dog_jpg/')


In [7]:
IMG_SIZE=75
cat_image_array=[]
for i in range(len(all_cat_image_names)):
    temp=plt.imread('downloads/cat_jpg/'+all_cat_image_names[i])
    temp=(cv2.resize(temp,(IMG_SIZE,IMG_SIZE)).T[0]).T
    temp=np.ndarray.flatten(temp).reshape(IMG_SIZE*IMG_SIZE)
    cat_image_array.append(temp)
    

    


In [9]:
dog_image_array=[]
for i in range(len(all_dog_image_names)):
    temp=plt.imread('downloads/dog_jpg/'+all_dog_image_names[i])
    temp=(cv2.resize(temp,(IMG_SIZE,IMG_SIZE)).T[0]).T
    temp=np.ndarray.flatten(temp).reshape(IMG_SIZE*IMG_SIZE)
    dog_image_array.append(temp)
    


In [10]:
dog_image_array=np.array(dog_image_array)
cat_image_array=np.array(cat_image_array)

# normalistaion

In [11]:
cat_image_array=(cat_image_array-cat_image_array.mean(axis=0))/cat_image_array.std(axis=0)
dog_image_array=(dog_image_array-dog_image_array.mean(axis=0))/dog_image_array.std(axis=0)

In [12]:
cat_image_df=pd.DataFrame(cat_image_array)
dog_image_df=pd.DataFrame(dog_image_array)

In [13]:
# calculating covariance matrices
cov_cat = cat_image_df.cov()
cov_dog = dog_image_df.cov()


In [113]:
mean_cat=(np.array(cat_image_array.mean(axis=0))).reshape(len(cat_image_array.T),1)
mean_dog=(np.array(dog_image_array.mean(axis=0))).reshape(len(dog_image_array.T),1)

# creating actual answers Y

In [62]:
Y=[]
Y.extend(["cat"]*91)   # first 91 feature row is for cats, rest 96 is for dogs
Y.extend(["dog"]*96)
Y=np.array(Y)

# creating X array of pixels

In [54]:
X=np.array(pd.concat([cat_image_df,dog_image_df]))

In [55]:
X.shape

(187, 5625)

In [150]:
def multivariate_norm_pdf(x,mean,cov):
    
   # return (1/(((2*np.pi)**len(x.T) * (1))**0.5))* np.exp(-0.5* np.dot(np.dot((x-mean).T,np.linalg.inv(cov)) , (x-mean))[0][0] )
    a= (1/(((2*np.pi)**len(x.T) * (1))**0.5))* np.exp(-0.5* np.dot(np.dot((x-mean.T).T,np.linalg.inv(cov)) , (x-mean.T))[0][0] )
    print(a)

In [151]:
X[0]

array([-0.88037105, -0.98701567, -1.15242416, ..., -0.93552689,
       -0.9741287 , -0.72753066])

In [152]:
mean_cat

array([[ 1.15292391e-16],
       [-1.04922176e-16],
       [ 7.93016446e-18],
       ...,
       [-1.04922176e-16],
       [-1.09802277e-17],
       [-4.33108982e-17]])

In [153]:
multivariate_norm_pdf(X[0],mean_dog,cov_dog)

OverflowError: (34, 'Result too large')

In [158]:
np.exp(e)

array([[5.43569401e+136]])

In [142]:
a=(X[0]-mean_cat.T)

In [143]:
b=(X[0]-mean_cat.T).T

In [144]:
c=np.linalg.inv(cov_cat)

In [145]:
mu

In [146]:
d.shape

(1, 5625)

In [147]:
e=np.dot(d,b)

In [148]:
e.shape

(1, 1)

In [74]:
prior_cat=len(X[Y=="cat"])/len(X)
prior_cog=len(X[Y=="dog"])/len(X)

In [75]:
def posterior_normal(example,mean_cat,cov_cat,mean_dog,cov_dog):   
    numerator_cat= multivariate_norm_pdf(example,mean_cat,cov_cat)*prior_cat
    numerator_dog= multivariate_norm_pdf(example,mean_dog,cov_dog)*prior_cog
    return numerator_cat/(numerator_cat+numerator_dog)  ,  numerator_dog/(numerator_cat+numerator_dog)



In [76]:
def predict_using_normal(xtest):
    y_predicted=[]
    for i in range(0,len(xtest)):
        
        posterior_cat,posterior_dog=posterior_normal(xtest[i],mean_cat,cov_cat,mean_dog,cov_dog)
        if posterior_cat>posterior_dog:
            y_predicted.append("cat")
        else:
            y_predicted.append("dog")
    y_predicted=(np.array(y_predicted)).reshape(len(y_predicted),1)
    return y_predicted.reshape(len(y_predicted),1)



def accuracy(y_predicted,y_actual):
    #y_actual=y_actual.reshape(len(y_actual),1)
    return 100*(len(Y[y_predicted==y_actual])/len(y_predicted))
    

In [88]:
#posterior_normal(X[0],mean_cat,cov_cat,mean_dog,cov_dog)

OverflowError: (34, 'Result too large')

In [30]:
X=pd.concat([cat_image_df,dog_image_df])